# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://Localhost:3306/shoppingmail
    username: root
    password: green502

# mybatis config

mybatis:
  type-aliases-package: com.green.shoppingmall
  mapper-locations: mapper/**/*.xml


# swagger
springdoc:
  swagger-ui:
    path: /swagger.html


file:
  dir: D:/download/shoppingmall